### ISSUE TITLE
Bad error message/code

### ISSUE THREAD

**Issue by sqs** [shurcooL/home#3]
Going to the nonexistent URL https://dmitri.shuralyov.com/blog/1822 yields an HTTP 200 (should be 404) and the following non-nice error page:

```
template: issue.html.tmpl:13:13: executing "issue" at <.Issue>: error calling Issue: open /home/dmitri/Dropbox/Store/issues/dmitri.shuralyov.com/blog/issues/1822/0: no such file or directory
```

**Comment by shurcooL** [comment]
Thanks for reporting this Quinn! 😁

This is a known issue in `issuesapp`. I've been deferring resolving it because it'll no longer be an issue after I eventually change that codebase to a new architecture with better error handling. 😛

But that won't happen soon, so I'll just fix this specific case for now. Returning 404 is the right thing to do.
