### ISSUE TITLE
Get "https://dmitri.shuralyov.com/gpu/mtl?go-get=1": dial tcp 172.93.50.41:443: i/o timeout

### ISSUE THREAD

**Issue by sudo-suhas** [shurcooL/home#42]
Facing this issue while running go get:
```
 go: github.com/spf13/viper@v1.7.1 requires
	github.com/bketelsen/crypt@v0.0.3-0.20200106085610-5cbc8cc4026c requires
	cloud.google.com/go/firestore@v1.1.0 requires
	golang.org/x/exp@v0.0.0-20191030013958-a1ab85dbe136 requires
	dmitri.shuralyov.com/gpu/mtl@v0.0.0-20190408044501-666a987793e9: unrecognized import path "dmitri.shuralyov.com/gpu/mtl": https fetch: Get "https://dmitri.shuralyov.com/gpu/mtl?go-get=1": dial tcp 172.93.50.41:443: i/o timeout
```

I am not able to access `https://dmitri.shuralyov.com/gpu/mtl?go-get=1` from my local system either. Is it down?

**Comment by sudo-suhas** [comment]
```
$ curl -i https://dmitri.shuralyov.com
curl: (7) Failed to connect to dmitri.shuralyov.com port 443: Operation timed out
```

**Comment by dmitshur** [comment]
Thanks for reporting.

This particular outage should be resolved by now. I'll update this issue with more information about what happened later.

In general, I suggest using a module proxy, for example the Go module mirror (https://proxy.golang.org), or your own proxy, or a combination of them, in order to be able to download modules even when some origin server is temporarily unavailable. If you're using Go 1.13 or newer, the default value of `GOPROXY` environment variable includes `https://proxy.golang.org` in it. See [go command documentation](https://golang.org/cmd/go/#hdr-Module_downloading_and_verification) for more information.

**Comment by akfaew** [comment]
> In general, I suggest using a module proxy

Sometimes it's not that easy, see: https://github.com/golang/go/issues/35221
